myblog/blog/urls.py
from django.conf.urls import url

from . import views
app_name='blog'
urlpatterns=[
	url(r'^$',views.index,name='index'),
	url(r'^article/(?P<article_id>[0-9]+)/$', views.view_article, name='view_article'),
	url(r'^genre/(?P<genre_id>[0-9]+)/$',views.view_genre, name='view_genre'),
]


myblog/myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^blog/',include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

myblog/blog/models.py
import datetime
from django.db import models
from django.db.models import permalink
from django.utils import timezone
# Create your models here.
class Genre(models.Model):
	title=models.CharField(max_length=30)
	'''slug = models.SlugField(max_length=100, unique=True)'''
	def __str__(self):
		return self.title
	'''@permalink
	def get_absolute_url(self):
		return ('view_blog_category', None, { 'slug': self.slug })'''

class Article(models.Model):
	title=models.CharField(max_length=50)
	'''slug = models.SlugField(max_length=100, unique=True)'''
	body = models.TextField()
	body=models.TextField()
	posted=models.DateTimeField('date published')
	genre=models.ForeignKey(Genre,on_delete=models.CASCADE)
	def __str__(self):
		return self.title
	'''@permalink
	def get_absolute_url(self):
		return ('view_blog_post', None, { 'slug': self.slug })'''


myblog/blog/views.py
from django.http import HttpResponse,Http404
from django.shortcuts import render

from .models import Article,Genre 
def index(request):
    return render(request,'blog/index.html',{'genres':Genre.objects.all(),'articles':Article.objects.all()[:3]})

def view_article(request, article_id):
	try:
		a=Article.objects.get(pk=article_id)
	except Article.DoesNotExist:
		raise Http404("Article Doesn't Exist!")
	return render(request,'blog/view_article.html',{'article':a})

def view_genre(request, genre_id):
	try:
		g=Genre.objects.get(pk=genre_id)
	except Genre.DoesNotExist:
		raise Http404("Genre Doesn't Exist!")
	return render(request,'blog/view_genre.html',{'genre':g,'articles':Article.objects.filter(genre=g)[:5]})

myblog/blog/templates/blog/index.html

{% block content %}
    
    <h2>Articles</h2>
    {% if articles %}
        <ul>
        {% for art in articles %}
            <li><a href="{% url 'blog:view_article' art.id %}">{{ art.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no Articles.</p>
    {% endif %}

    <h2>Genre</h2>
    {% if genres %}
        <ul>
        {% for g in genres %}
            <li><a href=" {% url 'blog:view_genre' g.id %}">{{ g.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no Genre.</p>
    {% endif %}

{% endblock %}



myblog/blog/templates/blog/view_article.html
<html>
<title>{{ article.title }}</title>
<head></head>
<body>
<h1>{{ article.title }}</h1>

{{ article.body }}
</body>
</html>

myblog/blog/templates/blog/view_genre.html

{% block title %}{{ genre.title }}{% endblock %}

{% block content %}
    {% if articles %}
        <ul>
        {% for art in articles %}
            <li><a href="{% url 'blog:view_article' art.id %}">{{ art.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no Articles.</p>
    {% endif %}
{% endblock %}